# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import magellan_pb2 as magellan__pb2


class gRPCStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SetVariable = channel.unary_unary(
        '/magellan.gRPC/SetVariable',
        request_serializer=magellan__pb2.Variable.SerializeToString,
        response_deserializer=magellan__pb2.Response.FromString,
        )


class gRPCServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SetVariable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_gRPCServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SetVariable': grpc.unary_unary_rpc_method_handler(
          servicer.SetVariable,
          request_deserializer=magellan__pb2.Variable.FromString,
          response_serializer=magellan__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'magellan.gRPC', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
